[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py38"
line-length = 120
exclude = [
  ".git",
  ".tox",
  "build",
  "dist",
  "venv*",
]

[tool.ruff.lint]
select = ["E", "F"]
extend-select = ["W", "B", "C4", "PERF", "A"]
ignore = [
    "F401",
    "F403",
    "F405",
    "F821",
    "F632",
    "E711",
    "E721",
]

[tool.isort]
py_version = 38
line_length = 120
skip_gitignore = true
lines_after_imports = 2
force_single_line = true
include_trailing_comma = true
atomic = true
honor_noqa = true
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
default_section = "THIRDPARTY"
known_first_party = ["steem", "steembase"]

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true
follow_imports = "silent"
show_error_codes = true
pretty = true
check_untyped_defs = false
warn_return_any = false
warn_unused_ignores = false
disable_error_code = ["attr-defined", "name-defined", "call-arg", "arg-type", "assignment", "index", "operator", "misc"]
exclude = "^(build|dist|\\.tox|venv.*)/"

[tool.pytest.ini_options]
norecursedirs = ["dist", "docs", "build", "deploy"]
addopts = "-ra"
testpaths = ["tests"]
